const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('oleAPI', {
    hideWindow: () => ipcRenderer.send('hide-window'),
    onRoutine: (cb) => ipcRenderer.on('routine-trigger', (_e, id) => cb(id)),
    health: {
        getSummary: () => ipcRenderer.invoke('health:get-summary'),
        getTrends:  (metric, days) => ipcRenderer.invoke('health:get-trends', metric, days),
        refresh:    () => ipcRenderer.invoke('health:refresh'),
        onReady:    (cb) => ipcRenderer.on('health:ready', (_e, payload) => cb(payload)),
        onProgress: (cb) => ipcRenderer.on('health:progress', (_e, payload) => cb(payload)),
    },
    strava: {
        status:         () => ipcRenderer.invoke('strava:status'),
        connect:        () => ipcRenderer.invoke('strava:connect'),
        disconnect:     () => ipcRenderer.invoke('strava:disconnect'),
        listActivities: (opts) => ipcRenderer.invoke('strava:list-activities', opts),
        sync:           (opts) => ipcRenderer.invoke('strava:sync', opts),
        getActivity:    (id) => ipcRenderer.invoke('strava:get-activity', id),
        onStatus:       (cb) => ipcRenderer.on('strava:status', (_e, payload) => cb(payload)),
        onActivities:   (cb) => ipcRenderer.on('strava:activities', (_e, payload) => cb(payload)),
    },
    plan: {
        getCurrent: () => ipcRenderer.invoke('plan:get-current'),
        generate:   (opts) => ipcRenderer.invoke('plan:generate', opts),
        markDone:   (date, done) => ipcRenderer.invoke('plan:mark-done', { date, done }),
        updateDay:  (date, patch) => ipcRenderer.invoke('plan:update-day', { date, patch }),
        clear:      () => ipcRenderer.invoke('plan:clear'),
        onUpdated:  (cb) => ipcRenderer.on('plan:updated', (_e, payload) => cb(payload)),
        onDoneUpdated: (cb) => ipcRenderer.on('plan:done-updated', (_e, payload) => cb(payload)),
    },
    todo: {
        getAll:     () => ipcRenderer.invoke('todo:get-all'),
        add:        (partial)     => ipcRenderer.invoke('todo:add', partial),
        update:     (id, patch)   => ipcRenderer.invoke('todo:update', { id, patch }),
        remove:     (id)          => ipcRenderer.invoke('todo:remove', id),
        toggleDone: (id)          => ipcRenderer.invoke('todo:toggle', id),
        reorder:    (orderedIds)  => ipcRenderer.invoke('todo:reorder', orderedIds),
        migrate:    (legacyItems) => ipcRenderer.invoke('todo:migrate', legacyItems),
        onUpdated:  (cb) => ipcRenderer.on('todo:updated', (_e, payload) => cb(payload)),
    },
    coach: {
        send:       ({ apiKey, userMessage }) => ipcRenderer.invoke('coach:send', { apiKey, userMessage }),
        clear:      () => ipcRenderer.invoke('coach:clear'),
        getHistory: () => ipcRenderer.invoke('coach:get-history'),
        onHistoryUpdated: (cb) => ipcRenderer.on('coach:history-updated', (_e, payload) => cb(payload)),
        onToolEvent:      (cb) => ipcRenderer.on('coach:tool-event', (_e, payload) => cb(payload)),
    },
    calendar: {
        list:           () => ipcRenderer.invoke('calendar:list'),
        refreshNow:     () => ipcRenderer.invoke('calendar:refresh-now'),
        listSubs:       () => ipcRenderer.invoke('calendar:list-subs'),
        addSub:         ({ label, url }) => ipcRenderer.invoke('calendar:add-sub', { label, url }),
        removeSub:      (id) => ipcRenderer.invoke('calendar:remove-sub', id),
        addInternal:    (partial) => ipcRenderer.invoke('calendar:add-internal', partial),
        updateInternal: (id, patch, event) => ipcRenderer.invoke('calendar:update-internal', { id, patch, event }),
        deleteInternal: (idOrEvent) => ipcRenderer.invoke('calendar:delete-internal', idOrEvent),
        onUpdated:      (cb) => ipcRenderer.on('calendar:updated', (_e, payload) => cb(payload)),
        caldav: {
            status:        () => ipcRenderer.invoke('calendar:caldav-status'),
            connect:       ({ appleId, password }) => ipcRenderer.invoke('calendar:caldav-connect', { appleId, password }),
            disconnect:    () => ipcRenderer.invoke('calendar:caldav-disconnect'),
            listCalendars: () => ipcRenderer.invoke('calendar:caldav-list-calendars'),
            setVisible:    (urls) => ipcRenderer.invoke('calendar:caldav-set-visible', urls),
            setTarget:     (url) => ipcRenderer.invoke('calendar:caldav-set-target', url),
        },
    },
})
