const { contextBridge, ipcRenderer } = require('electron')

// Hilfsfunktion: registriert Listener + gibt Cleanup zurück
function on(channel, cb) {
    const handler = (_e, payload) => cb(payload)
    ipcRenderer.on(channel, handler)
    return () => ipcRenderer.removeListener(channel, handler)
}

contextBridge.exposeInMainWorld('oleAPI', {
    hideWindow: () => ipcRenderer.send('hide-window'),
    onRoutine: (cb) => on('routine-trigger', (id) => cb(id)),
    health: {
        getSummary:   () => ipcRenderer.invoke('health:get-summary'),
        getTrends:    (metric, days) => ipcRenderer.invoke('health:get-trends', metric, days),
        refresh:      () => ipcRenderer.invoke('health:refresh'),
        sourceStatus: () => ipcRenderer.invoke('health:source-status'),
        onReady:      (cb) => on('health:ready', cb),
        onProgress:   (cb) => on('health:progress', cb),
    },
    strava: {
        status:         () => ipcRenderer.invoke('strava:status'),
        connect:        () => ipcRenderer.invoke('strava:connect'),
        disconnect:     () => ipcRenderer.invoke('strava:disconnect'),
        listActivities: (opts) => ipcRenderer.invoke('strava:list-activities', opts),
        sync:           (opts) => ipcRenderer.invoke('strava:sync', opts),
        getActivity:    (id) => ipcRenderer.invoke('strava:get-activity', id),
        onStatus:       (cb) => on('strava:status', cb),
        onActivities:   (cb) => on('strava:activities', cb),
    },
    coros: {
        status:      () => ipcRenderer.invoke('coros:status'),
        connect:     () => ipcRenderer.invoke('coros:connect'),
        disconnect:  () => ipcRenderer.invoke('coros:disconnect'),
        getSummary:  () => ipcRenderer.invoke('coros:get-summary'),
        getTrends:   (metric, days) => ipcRenderer.invoke('coros:get-trends', { metric, days }),
        refresh:     () => ipcRenderer.invoke('coros:refresh'),
        onStatus:    (cb) => on('coros:status', cb),
        onReady:     (cb) => on('coros:ready', cb),
    },
    plan: {
        getCurrent:    () => ipcRenderer.invoke('plan:get-current'),
        generate:      (opts) => ipcRenderer.invoke('plan:generate', opts),
        markDone:      (date, done) => ipcRenderer.invoke('plan:mark-done', { date, done }),
        updateDay:     (date, patch) => ipcRenderer.invoke('plan:update-day', { date, patch }),
        clear:         () => ipcRenderer.invoke('plan:clear'),
        onUpdated:     (cb) => on('plan:updated', cb),
        onDoneUpdated: (cb) => on('plan:done-updated', cb),
    },
    todo: {
        getAll:     () => ipcRenderer.invoke('todo:get-all'),
        add:        (partial)     => ipcRenderer.invoke('todo:add', partial),
        update:     (id, patch)   => ipcRenderer.invoke('todo:update', { id, patch }),
        remove:     (id)          => ipcRenderer.invoke('todo:remove', id),
        toggleDone: (id)          => ipcRenderer.invoke('todo:toggle', id),
        reorder:    (orderedIds)  => ipcRenderer.invoke('todo:reorder', orderedIds),
        migrate:    (legacyItems) => ipcRenderer.invoke('todo:migrate', legacyItems),
        onUpdated:  (cb) => on('todo:updated', cb),
    },
    routine: {
        getAll:      ()                  => ipcRenderer.invoke('routine:get-all'),
        setWakeTime: (routineId, time)   => ipcRenderer.invoke('routine:set-wake-time', { routineId, time }),
        updateSteps: (routineId, steps)  => ipcRenderer.invoke('routine:update-steps', { routineId, steps }),
        onUpdated:   (cb) => on('routine:updated', cb),
    },
    habit: {
        getAll:    ()                      => ipcRenderer.invoke('habit:get-all'),
        add:       (partial)               => ipcRenderer.invoke('habit:add', partial),
        update:    ({ id, patch })         => ipcRenderer.invoke('habit:update', { id, patch }),
        remove:    ({ id })                => ipcRenderer.invoke('habit:remove', { id }),
        checkin:   ({ id, date, done })    => ipcRenderer.invoke('habit:checkin', { id, date, done }),
        onUpdated: (cb) => on('habit:updated', cb),
    },
    coach: {
        send:             ({ apiKey, userMessage }) => ipcRenderer.invoke('coach:send', { apiKey, userMessage }),
        clear:            () => ipcRenderer.invoke('coach:clear'),
        getHistory:       () => ipcRenderer.invoke('coach:get-history'),
        onHistoryUpdated: (cb) => on('coach:history-updated', cb),
        onToolEvent:      (cb) => on('coach:tool-event', cb),
        onStreamDelta:    (cb) => on('coach:stream-delta', cb),
        onStreamReset:    (cb) => on('coach:stream-reset', cb),
    },
    vault: {
        getSettings:    () => ipcRenderer.invoke('vault:get-settings'),
        setPath:        () => ipcRenderer.invoke('vault:set-path'),
        setAutoExport:  (enabled) => ipcRenderer.invoke('vault:set-auto-export', enabled),
        setExportCoach: (enabled) => ipcRenderer.invoke('vault:set-export-coach', enabled),
        exportDay:      (date) => ipcRenderer.invoke('vault:export-day', date),
        exportToday:    () => ipcRenderer.invoke('vault:export-today'),
        exportRange:    (from, to) => ipcRenderer.invoke('vault:export-range', { from, to }),
        onUpdated:      (cb) => on('vault:updated', cb),
    },
    kitchen: {
        getAll:          () => ipcRenderer.invoke('kitchen:get-all'),
        costReport:      () => ipcRenderer.invoke('kitchen:cost-report'),
        importReceipt:   (apiKey) => ipcRenderer.invoke('kitchen:import-receipt', { apiKey }),
        confirmImport:   (items) => ipcRenderer.invoke('kitchen:confirm-import', items),
        invAdd:          (partial) => ipcRenderer.invoke('kitchen:inv-add', partial),
        invUpdate:       (id, patch) => ipcRenderer.invoke('kitchen:inv-update', { id, patch }),
        invRemove:       (id) => ipcRenderer.invoke('kitchen:inv-remove', id),
        invConsume:      (id, amount) => ipcRenderer.invoke('kitchen:inv-consume', { id, amount }),
        mealEstimate:    (opts) => ipcRenderer.invoke('kitchen:meal-estimate', opts),
        mealAdd:         (partial) => ipcRenderer.invoke('kitchen:meal-add', partial),
        mealUpdate:      (id, patch) => ipcRenderer.invoke('kitchen:meal-update', { id, patch }),
        mealRemove:      (id) => ipcRenderer.invoke('kitchen:meal-remove', id),
        recipeGenerate:  (opts) => ipcRenderer.invoke('kitchen:recipe-generate', opts),
        recipeSave:      (recipe) => ipcRenderer.invoke('kitchen:recipe-save', recipe),
        recipeUpdate:    (id, patch) => ipcRenderer.invoke('kitchen:recipe-update', { id, patch }),
        recipeRemove:    (id) => ipcRenderer.invoke('kitchen:recipe-remove', id),
        applyConsumption:(reductions) => ipcRenderer.invoke('kitchen:apply-consumption', reductions),
        macroProfileUpdate: (category, patch) => ipcRenderer.invoke('kitchen:macro-profile-update', { category, patch }),
        macroOverride:   (date, macros) => ipcRenderer.invoke('kitchen:macro-override', { date, macros }),
        dayplanGenerate: (opts) => ipcRenderer.invoke('kitchen:dayplan-generate', opts),
        prepGenerate:    (opts) => ipcRenderer.invoke('kitchen:prep-generate', opts),
        onUpdated:       (cb) => on('kitchen:updated', cb),
    },
    debrief: {
        get:       (date) => ipcRenderer.invoke('debrief:get', date),
        set:       (date, patch) => ipcRenderer.invoke('debrief:set', { date, patch }),
        onUpdated: (cb) => on('debrief:updated', cb),
    },
    trainingLog: {
        get:           (date) => ipcRenderer.invoke('traininglog:get', date),
        set:           (date, patch) => ipcRenderer.invoke('traininglog:set', { date, patch }),
        recentNiggles: (days) => ipcRenderer.invoke('traininglog:recent-niggles', days),
        onUpdated:     (cb) => on('traininglog:updated', cb),
    },
    calendar: {
        list:           () => ipcRenderer.invoke('calendar:list'),
        refreshNow:     () => ipcRenderer.invoke('calendar:refresh-now'),
        listSubs:       () => ipcRenderer.invoke('calendar:list-subs'),
        addSub:         ({ label, url }) => ipcRenderer.invoke('calendar:add-sub', { label, url }),
        removeSub:      (id) => ipcRenderer.invoke('calendar:remove-sub', id),
        addInternal:    (partial) => ipcRenderer.invoke('calendar:add-internal', partial),
        updateInternal: (id, patch, event) => ipcRenderer.invoke('calendar:update-internal', { id, patch, event }),
        deleteInternal: (idOrEvent) => ipcRenderer.invoke('calendar:delete-internal', idOrEvent),
        onUpdated:      (cb) => on('calendar:updated', cb),
        caldav: {
            status:        () => ipcRenderer.invoke('calendar:caldav-status'),
            connect:       ({ appleId, password }) => ipcRenderer.invoke('calendar:caldav-connect', { appleId, password }),
            disconnect:    () => ipcRenderer.invoke('calendar:caldav-disconnect'),
            listCalendars: () => ipcRenderer.invoke('calendar:caldav-list-calendars'),
            setVisible:    (urls) => ipcRenderer.invoke('calendar:caldav-set-visible', urls),
            setTarget:     (url) => ipcRenderer.invoke('calendar:caldav-set-target', url),
        },
    },
})
